import 'package:starinvest/src/common/image_paths.dart';

final List<Map<String, dynamic>> dummyPlayers = [
  {
    'name': 'Trent Alexander-Arnold',
    'price': '€99,999.99',
    'club': 'Liverpool',
    'image': ImagePaths.home.trent,
    'clubImage': ImagePaths.home.liverpool,
    'trend': 4.25,
    'isUp': true,
  },
  {
    'name': 'Kylian Mbappé',
    'price': '€95,000.00',
    'club': 'Real Madrid',
    'image': ImagePaths.home.mbappe,
    'clubImage': ImagePaths.home.realMadrid,
    'trend': 42.35,
    'isUp': true,
  },
  {
    'name': 'Viktor Gyökeres',
    'price': '€88,000.00',
    'club': 'Sporting CP',
    'image': ImagePaths.home.gyokeres,
    'clubImage': ImagePaths.home.sporting,
    'trend': 3.12,
    'isUp': true,
  },
  {
    'name': 'Julián Álvarez',
    'price': '€87,000.00',
    'club': 'Manchester City',
    'image': ImagePaths.home.alvarez,
    'clubImage': ImagePaths.home.manchesterCity,
    'trend': 7.45,
    'isUp': true,
  },
  {
    'name': 'Erling Haaland',
    'price': '€180,000.00',
    'club': 'Manchester City',
    'image': ImagePaths.home.haaland,
    'clubImage': ImagePaths.home.manchesterCity,
    'trend': 18.22,
    'isUp': true,
  },
  {
    'name': 'Vinícius Jr',
    'price': '€150,000.00',
    'club': 'Real Madrid',
    'image': ImagePaths.home.vinicius,
    'clubImage': ImagePaths.home.realMadrid,
    'trend': 15.67,
    'isUp': true,
  },
  {
    'name': 'Bukayo Saka',
    'price': '€130,000.00',
    'club': 'Arsenal',
    'image': ImagePaths.home.saka,
    'clubImage': ImagePaths.home.arsenal,
    'trend': 12.85,
    'isUp': true,
  },
  {
    'name': 'Pedri González',
    'price': '€120,000.00',
    'club': 'FC Barcelona',
    'image': ImagePaths.home.pedri,
    'clubImage': ImagePaths.home.fcb,
    'trend': -2.15,
    'isUp': false,
  },
  {
    'name': 'Florian Wirtz',
    'price': '€110,000.00',
    'club': 'Bayer Leverkusen',
    'image': ImagePaths.home.wirtz,
    'clubImage': ImagePaths.home.leverkusen,
    'trend': 9.48,
    'isUp': true,
  },
  {
    'name': 'Jude Bellingham',
    'price': '€180,000.00',
    'club': 'Real Madrid',
    'image': ImagePaths.home.bellingham,
    'clubImage': ImagePaths.home.realMadrid,
    'trend': 25.75,
    'isUp': true,
  },
  {
    'name': 'Phil Foden',
    'price': '€115,000.00',
    'club': 'Manchester City',
    'image': ImagePaths.home.foden,
    'clubImage': ImagePaths.home.manchesterCity,
    'trend': 10.25,
    'isUp': true,
  },
  {
    'name': 'Lautaro Martínez',
    'price': '€95,000.00',
    'club': 'Inter Milan',
    'image': ImagePaths.home.martinez,
    'clubImage': ImagePaths.home.inter,
    'trend': 6.52,
    'isUp': true,
  },
  {
    'name': 'Khvicha Kvaratskhelia',
    'price': '€90,000.00',
    'club': 'Napoli',
    'image': ImagePaths.home.kvaratskhelia,
    'clubImage': ImagePaths.home.napoli,
    'trend': -1.84,
    'isUp': false,
  },
  {
    'name': 'Rafael Leão',
    'price': '€100,000.00',
    'club': 'AC Milan',
    'image': ImagePaths.home.leao,
    'clubImage': ImagePaths.home.milan,
    'trend': 8.35,
    'isUp': true,
  },
  {
    'name': 'Jamal Musiala',
    'price': '€120,000.00',
    'club': 'Bayern Munich',
    'image': ImagePaths.home.musiala,
    'clubImage': ImagePaths.home.bayern,
    'trend': 6.72,
    'isUp': true,
  },
  {
    'name': 'Rodrygo Goes',
    'price': '€90,000.00',
    'club': 'Real Madrid',
    'image': ImagePaths.home.rodrygo,
    'clubImage': ImagePaths.home.realMadrid,
    'trend': 5.42,
    'isUp': true,
  },
  {
    'name': 'Martin Ødegaard',
    'price': '€100,000.00',
    'club': 'Arsenal',
    'image': ImagePaths.home.odegaard,
    'clubImage': ImagePaths.home.arsenal,
    'trend': 9.64,
    'isUp': true,
  },
  {
    'name': 'João Félix',
    'price': '€85,000.00',
    'club': 'FC Barcelona',
    'image': ImagePaths.home.felix,
    'clubImage': ImagePaths.home.fcb,
    'trend': -4.38,
    'isUp': false,
  },
  {
    'name': 'Gavi',
    'price': '€95,000.00',
    'club': 'FC Barcelona',
    'image': ImagePaths.home.gavi,
    'clubImage': ImagePaths.home.fcb,
    'trend': 3.47,
    'isUp': true,
  },
  {
    'name': 'Marcus Rashford',
    'price': '€120,000.00',
    'club': 'Manchester United',
    'image': ImagePaths.home.rashford,
    'clubImage': ImagePaths.home.manchesterUnited,
    'trend': -5.26,
    'isUp': false,
  },
  {
    'name': 'Leroy Sané',
    'price': '€85,000.00',
    'club': 'Bayern Munich',
    'image': ImagePaths.home.sane,
    'clubImage': ImagePaths.home.bayern,
    'trend': 4.95,
    'isUp': true,
  },
  {
    'name': 'Ferran Torres',
    'price': '€65,000.00',
    'club': 'FC Barcelona',
    'image': ImagePaths.home.ferran,
    'clubImage': ImagePaths.home.fcb,
    'trend': -2.78,
    'isUp': false,
  },
  {
    'name': 'Federico Valverde',
    'price': '€110,000.00',
    'club': 'Real Madrid',
    'image': ImagePaths.home.valverde,
    'clubImage': ImagePaths.home.realMadrid,
    'trend': 8.12,
    'isUp': true,
  },
  {
    'name': 'Declan Rice',
    'price': '€100,000.00',
    'club': 'Arsenal',
    'image': ImagePaths.home.rice,
    'clubImage': ImagePaths.home.arsenal,
    'trend': 5.98,
    'isUp': true,
  },
  {
    'name': 'Enzo Fernández',
    'price': '€80,000.00',
    'club': 'Chelsea',
    'image': ImagePaths.home.enzo,
    'clubImage': ImagePaths.home.chelsea,
    'trend': -3.12,
    'isUp': false,
  },
  {
    'name': 'Christopher Nkunku',
    'price': '€95,000.00',
    'club': 'Chelsea',
    'image': ImagePaths.home.nkunku,
    'clubImage': ImagePaths.home.chelsea,
    'trend': 2.54,
    'isUp': true,
  },
  {
    'name': 'Alejandro Garnacho',
    'price': '€75,000.00',
    'club': 'Manchester United',
    'image': ImagePaths.home.garnacho,
    'clubImage': ImagePaths.home.manchesterUnited,
    'trend': 10.15,
    'isUp': true,
  },
  {
    'name': 'Nico Williams',
    'price': '€70,000.00',
    'club': 'Athletic Bilbao',
    'image': ImagePaths.home.nico,
    'clubImage': ImagePaths.home.bilbao,
    'trend': 4.62,
    'isUp': true,
  },
  {
    'name': 'Xavi Simons',
    'price': '€85,000.00',
    'club': 'RB Leipzig',
    'image': ImagePaths.home.simons,
    'clubImage': ImagePaths.home.rbl,
    'trend': 12.38,
    'isUp': true,
  },
  {
    'name': 'Rasmus Højlund',
    'price': '€80,000.00',
    'club': 'Manchester United',
    'image': ImagePaths.home.hojlund,
    'clubImage': ImagePaths.home.manchesterUnited,
    'trend': 6.41,
    'isUp': true,
  },
  {
    'name': 'Frenkie de Jong',
    'price': '€90,000.00',
    'club': 'FC Barcelona',
    'image': ImagePaths.home.dejong,
    'clubImage': ImagePaths.home.fcb,
    'trend': -1.92,
    'isUp': false,
  },
  {
    'name': 'Joshua Kimmich',
    'price': '€105,000.00',
    'club': 'Bayern Munich',
    'image': ImagePaths.home.kimmich,
    'clubImage': ImagePaths.home.bayern,
    'trend': 2.73,
    'isUp': true,
  },
  {
    'name': 'Casemiro',
    'price': '€70,000.00',
    'club': 'Manchester United',
    'image': ImagePaths.home.casemiro,
    'clubImage': ImagePaths.home.manchesterUnited,
    'trend': -3.88,
    'isUp': false,
  },
  {
    'name': 'Sandro Tonali',
    'price': '€85,000.00',
    'club': 'Newcastle United',
    'image': ImagePaths.home.tonali,
    'clubImage': ImagePaths.home.newcastle,
    'trend': -6.74,
    'isUp': false,
  },
  {
    'name': 'Bernardo Silva',
    'price': '€90,000.00',
    'club': 'Manchester City',
    'image': ImagePaths.home.bernardo,
    'clubImage': ImagePaths.home.manchesterCity,
    'trend': 3.45,
    'isUp': true,
  },
  {
    'name': 'Jack Grealish',
    'price': '€80,000.00',
    'club': 'Manchester City',
    'image': ImagePaths.home.grealish,
    'clubImage': ImagePaths.home.manchesterCity,
    'trend': -1.24,
    'isUp': false,
  },
  {
    'name': 'Bruno Fernandes',
    'price': '€95,000.00',
    'club': 'Manchester United',
    'image': ImagePaths.home.bruno,
    'clubImage': ImagePaths.home.manchesterUnited,
    'trend': 5.26,
    'isUp': true,
  },
  {
    'name': 'Mohamed Salah',
    'price': '€100,000.00',
    'club': 'Liverpool',
    'image': ImagePaths.home.salah,
    'clubImage': ImagePaths.home.liverpool,
    'trend': 11.24,
    'isUp': true,
  },
  {
    'name': 'Darwin Núñez',
    'price': '€85,000.00',
    'club': 'Liverpool',
    'image': ImagePaths.home.nunez,
    'clubImage': ImagePaths.home.liverpool,
    'trend': 3.15,
    'isUp': true,
  },
  {
    'name': 'Son Heung-min',
    'price': '€90,000.00',
    'club': 'Tottenham Hotspur',
    'image': ImagePaths.home.son,
    'clubImage': ImagePaths.home.tottenham,
    'trend': 8.63,
    'isUp': true,
  },
  {
    'name': 'Harry Kane',
    'price': '€120,000.00',
    'club': 'Bayern Munich',
    'image': ImagePaths.home.kane,
    'clubImage': ImagePaths.home.bayern,
    'trend': 14.52,
    'isUp': true,
  },
  {
    'name': 'Mason Mount',
    'price': '€70,000.00',
    'club': 'Manchester United',
    'image': ImagePaths.home.mount,
    'clubImage': ImagePaths.home.manchesterUnited,
    'trend': -7.32,
    'isUp': false,
  },
  {
    'name': 'Kai Havertz',
    'price': '€75,000.00',
    'club': 'Arsenal',
    'image': ImagePaths.home.havertz,
    'clubImage': ImagePaths.home.arsenal,
    'trend': 1.74,
    'isUp': true,
  },
  {
    'name': 'Raheem Sterling',
    'price': '€65,000.00',
    'club': 'Chelsea',
    'image': ImagePaths.home.sterling,
    'clubImage': ImagePaths.home.chelsea,
    'trend': -4.91,
    'isUp': false,
  },
  {
    'name': 'Antony',
    'price': '€60,000.00',
    'club': 'Manchester United',
    'image': ImagePaths.home.antony,
    'clubImage': ImagePaths.home.manchesterUnited,
    'trend': -5.67,
    'isUp': false,
  },
  {
    'name': 'Dominik Szoboszlai',
    'price': '€85,000.00',
    'club': 'Liverpool',
    'image': ImagePaths.home.szoboszlai,
    'clubImage': ImagePaths.home.liverpool,
    'trend': 7.13,
    'isUp': true,
  },
  {
    'name': 'Diogo Jota',
    'price': '€80,000.00',
    'club': 'Liverpool',
    'image': ImagePaths.home.jota,
    'clubImage': ImagePaths.home.liverpool,
    'trend': 3.65,
    'isUp': true,
  },
  {
    'name': 'Ousmane Dembélé',
    'price': '€90,000.00',
    'club': 'PSG',
    'image': ImagePaths.home.dembele,
    'clubImage': ImagePaths.home.psg,
    'trend': 5.92,
    'isUp': true,
  },
  {
    'name': 'Achraf Hakimi',
    'price': '€85,000.00',
    'club': 'PSG',
    'image': ImagePaths.home.hakimi,
    'clubImage': ImagePaths.home.psg,
    'trend': 2.14,
    'isUp': true,
  },
  {
    'name': 'Theo Hernández',
    'price': '€90,000.00',
    'club': 'AC Milan',
    'image': ImagePaths.home.hernandez,
    'clubImage': ImagePaths.home.milan,
    'trend': 6.23,
    'isUp': true,
  },
  {
    'name': 'Eduardo Camavinga',
    'price': '€95,000.00',
    'club': 'Real Madrid',
    'image': ImagePaths.home.camavinga,
    'clubImage': ImagePaths.home.realMadrid,
    'trend': 9.42,
    'isUp': true,
  },
];
